### ISSUE TITLE
Deploy scoreboard app

### ISSUE THREAD

**Issue by jgrumboe** [ruromero/devconf#17]
Hello,
Is it also possible to deploy the scoreboard app "onprem" ?
I've found no deployment configuration.
Best regards,
Johannes

**Comment by ruromero** [comment]
Hi Johannes,
I have created a docker image and a template
https://github.com/ruromero/break-fix/blob/master/minishift-addons/scoreboard/scoreboard-template.yaml
https://hub.docker.com/r/ruromero/scoreboard/

Thanks and sorry for the delay :smile:
